Capa de presentacion y listo para su funcionamiento
AbrahamXTS/LasBichotitasKWIC pull request #16
Opened 2023-09-26 16:23 UTC by JonathanQu3v3do

#6

2023-09-26 16:28 UTC, AbrahamXTS requested changes

2023-09-26 16:28 UTC, AbrahamXTS commented on src/main/java/com/bichotitas/infrastructure/UI/cli.java
> +public class cli {
Esta clase debería llamarse CLI en mayusculas por convención de nombres, por fa

2023-09-26 17:26 UTC, JonathanQu3v3do commented on src/main/java/com/bichotitas/infrastructure/UI/cli.java
> +public class cli {
Oko

2023-09-26 17:33 UTC, JonathanQu3v3do commented on src/main/java/com/bichotitas/infrastructure/UI/cli.java
> +public class cli {
corregido

2023-09-27 07:08 UTC, Dianita-01 approved these changes

2023-09-27 13:27 UTC, AbrahamXTS approved these changes

2023-09-27 13:27 UTC, merged